name: Gatsby Deployment Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: yarn install

      - name: Type Check
        run: yarn run type-check

      - name: Build
        run: yarn run build

      - name: Deploy to Netlify
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: deploy
          folder: public
